## 01 Exploration des données

* ### Importation des librairies

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import os
import seaborn as sns
import plotly.express as px
from plotly.subplots import make_subplots
from plotly import graph_objects as go
import time
import warnings
warnings.filterwarnings("ignore")

%time

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 6.44 µs

* ### Chargement des données

In [2]:
%pwd

'/home/donerick/Challenge 30 Days ML/notebook'

In [3]:
os.chdir("./")

In [4]:
%pwd

'/home/donerick/Challenge 30 Days ML/notebook'

In [5]:
os.chdir("/home/donerick/Challenge 30 Days ML")

In [6]:
data_meteo = pd.read_csv("data/raw/hourly_meteo_data.csv")

data_air_quality = pd.read_csv("data/raw/hourly_quality_air_data.csv")

In [7]:
data_meteo.head()

,date,temperature_2m,relative_humidity_2m,precipitation,surface_pressure,apparent_temperature,wind_speed_80m,wind_direction_80m,temperature_80m,soil_temperature_18cm,soil_moisture_3_to_9cm
0,2025-12-19 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025-12-19 01:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2025-12-19 02:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2025-12-19 03:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2025-12-19 04:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
### analyse descriptive de la meteo data


data_meteo.describe()

,temperature_2m,relative_humidity_2m,precipitation,surface_pressure,apparent_temperature,wind_speed_80m,wind_direction_80m,temperature_80m,soil_temperature_18cm,soil_moisture_3_to_9cm
count,1858.000000,1858.000000,1858.000000,1858.000000,1858.000000,1858.000000,1858.000000,1858.000000,1633.000000,1633.000000
mean,29.273705,77.292250,0.026695,1008.929233,34.453479,15.916211,212.285082,28.036374,31.314234,0.116410
std,2.401448,13.147281,0.120258,1.774486,2.149986,5.411957,36.876996,1.501982,1.367326,0.010612
min,24.066500,27.000000,0.000000,1004.615540,29.267605,0.360000,4.763556,24.666500,28.216501,0.096000
25%,27.416500,66.000000,0.000000,1007.712245,33.144235,12.979984,195.651620,26.966501,30.166500,0.109000
50%,28.400000,80.000000,0.000000,1008.912415,33.900025,16.442187,208.705860,27.666500,31.216501,0.117000
75%,31.112375,89.000000,0.000000,1010.184785,35.409437,19.469976,228.073827,29.066500,32.466500,0.125000
max,36.666500,97.000000,1.600000,1014.215100,41.942250,31.688177,360.000000,33.966500,34.266500,0.142000

In [9]:
data_meteo.nunique()

date                      2376
temperature_2m             310
relative_humidity_2m        59
precipitation               16
surface_pressure          1396
apparent_temperature      1844
wind_speed_80m             984
wind_direction_80m        1092
temperature_80m            189
soil_temperature_18cm      119
soil_moisture_3_to_9cm      47
dtype: int64

#### verifions les valeurs manquantes

In [10]:
data_meteo.shape

(2376, 11)

In [11]:
def define_missing_values(data):
    missing_values = data.isnull().sum()
    ration_missing_values = missing_values / len(data) * 100
    missing_data = pd.DataFrame({
        "missing_values": missing_values,
        "ratio_missing_values": ration_missing_values
    })
    return missing_data.sort_values(by="ratio_missing_values", ascending=False)

missing_data_meteo = define_missing_values(data_meteo)
missing_data_air_quality = define_missing_values(data_air_quality)

In [12]:
missing_data_meteo

                        missing_values  ratio_missing_values
soil_temperature_18cm              743             31.271044
soil_moisture_3_to_9cm             743             31.271044
temperature_2m                     518             21.801347
wind_speed_80m                     518             21.801347
relative_humidity_2m               518             21.801347
precipitation                      518             21.801347
surface_pressure                   518             21.801347
temperature_80m                    518             21.801347
apparent_temperature               518             21.801347
wind_direction_80m                 518             21.801347
date                                 0              0.000000

In [13]:
### les types de données


data_meteo.dtypes

date                       object
temperature_2m            float64
relative_humidity_2m      float64
precipitation             float64
surface_pressure          float64
apparent_temperature      float64
wind_speed_80m            float64
wind_direction_80m        float64
temperature_80m           float64
soil_temperature_18cm     float64
soil_moisture_3_to_9cm    float64
dtype: object

* ### Visualisation

In [14]:
import numpy as np
def visualization_data(data):

    fig  = go.Figure(make_subplots(specs=[[{"secondary_y": True}]]))

    fig.add_trace(
        go.Scatter(
            x = data['date'],
            y= data['temperature_2m'],
            mode="lines+markers",
            name="Temperature 2m(°C)",
            line=dict(color="firebrick", width=2.5),
            marker=dict(size=5),
            hovertemplate="<b>%{y:.1f}°C</b><extra>Température</extra>",
        ), secondary_y=False)

    fig.add_trace(
        go.Scatter(
            x=data['date'],
            y = data['apparent_temperature'],
            mode="lines+markers",
            name="Temp Apparente(°C)",
            line=dict(color="royalblue", width=2.5),
            marker=dict(size=5),
            hovertemplate="<b>%{y:.1f}°C</b><extra>Température</extra>",
        ), secondary_y=False)
        


    fig.add_trace(
        go.Scatter(
            x=data['date'],
            y=data['wind_speed_80m'],
            mode="markers+lines",
            name="Vitesse du vent sur 80m",
            line=dict(color="green", width=2.5, dash='dashdot'),
            marker=dict(size=5),
            hovertemplate="<b>%{y:.1f}°C</b><extra>Température</extra>",
        ), secondary_y=False)
            
    

    fig.update_layout(
        title= dict(text = "Tempeature et vitesse du vent sur une periode de 03 mois"),
        xaxis = dict(
            title = dict(
            text="Date (h)"
            )
        ),
        yaxis= dict(
            title=dict(
            text="Humidité (%)"
            )
        ),
        template="plotly_white"
    )
    fig.show()

visualization_data(data_meteo)

In [15]:
def fig_hourly_profile(data) -> go.Figure:
    """Profil horaire moyen : température + humidité sur axes doubles."""

    data['date'] = pd.to_datetime(data['date'],utc=True)
    data['hour'] = data['date'].dt.hour
    data['month'] = data['date'].dt.month
    data['day_of_week'] = data['date'].dt.dayofweek
    
    hourly_profile = data.groupby("hour").agg({
        "temperature_2m": "mean",
        "relative_humidity_2m": "mean",
        "wind_speed_80m": "mean",
        "surface_pressure": "mean",
        'temperature_80m': "mean"
    }).round(4).reset_index()

    fig  = go.Figure(make_subplots(specs=[[{"secondary_y": True}]]))
    fig.add_trace(go.Scatter(
        x=hourly_profile["hour"],
        y=hourly_profile["temperature_2m"],
        mode="lines+markers",
        name="Temp (°C)",
        line=dict(color="blue", width=2.5),
        marker=dict(size=5),
        hovertemplate="<b>%{y:.1f}°C</b><extra>Température</extra>",
    ), secondary_y=False)
 
    fig.add_trace(go.Scatter(
        x=hourly_profile["hour"],
        y=hourly_profile["relative_humidity_2m"],
        mode="lines+markers",
        name="Humidité (%)",
        line=dict(color="green", width=2.5),
        marker=dict(size=5),
        hovertemplate="<b>%{y:.1f}%</b><extra>Humidité</extra>",
    ), secondary_y=True)
 
    fig.add_trace(go.Scatter(
        x=hourly_profile["hour"],
        y=hourly_profile["wind_speed_80m"],
        mode="lines",
        name="Vent (km/h)",
        line=dict(color="teal", width=1.5, dash="dash"),
        hovertemplate="<b>%{y:.1f} km/h</b><extra>Vent</extra>",
    ), secondary_y=False)
    
    fig.add_trace(go.Scatter(
        x=hourly_profile["hour"],
        y=hourly_profile["surface_pressure"],
        mode="lines",
        name="Pression (hPa)",
        line=dict(color="orange", width=1.5, dash="dot"),
        hovertemplate="<b>%{y:.1f} hPa</b><extra>Pression</extra>",
    ), secondary_y=False)

    fig.add_trace(go.Scatter(
        x=hourly_profile["hour"],
        y=hourly_profile["temperature_80m"],
        mode="lines",
        name="Temp 80m (°C)",
        line=dict(color="red", width=1.5, dash="dot"),
        hovertemplate="<b>%{y:.1f}°C</b><extra>Temp 80m</extra>",
    ), secondary_y=False)

    fig.update_xaxes(title_text="Heure (UTC)", tickvals=list(range(0, 24, 2)))
    fig.update_yaxes(title_text="Temp / Vent", secondary_y=False, gridcolor="#b6b2a6")
    fig.update_yaxes(title_text="Humidité (%)", secondary_y=True, showgrid=False)
    fig.update_yaxes(title_text="Pression (hPa)", secondary_y=False, gridcolor="#347dbc")
    fig.update_yaxes(title_text="Temp 80m (°C)", secondary_y=False, gridcolor="#6b471c")
    fig.update_layout(
        template="plotly_white",
        height=340,
        margin=dict(l=10, r=10, t=10, b=10),
        legend=dict(orientation="h", y=1.08),
        hovermode="x unified",
    )
    return fig

fig_hourly_profile(data_meteo).show()

In [16]:
def features_of_date(data):

    data['date'] = pd.to_datetime(data['date'],utc=True)
    data['hour'] = data['date'].dt.hour
    data['month'] = data['date'].dt.month
    data['day_of_week'] = data['date'].dt.dayofweek
    return data

features_of_date(data=data_meteo)

,date,temperature_2m,relative_humidity_2m,precipitation,surface_pressure,apparent_temperature,wind_speed_80m,wind_direction_80m,temperature_80m,soil_temperature_18cm,soil_moisture_3_to_9cm,hour,month,day_of_week
0,2025-12-19 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,12,4
1,2025-12-19 01:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12,4
2,2025-12-19 02:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,12,4
3,2025-12-19 03:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,12,4
4,2025-12-19 04:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,12,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2371,2026-03-27 19:00:00+00:00,29.2665,78.0,0.0,1005.71830,34.078860,18.792551,200.17073,28.166500,34.016500,0.097,19,3,4
2372,2026-03-27 20:00:00+00:00,28.5165,82.0,0.0,1006.51587,33.833633,16.179985,200.85454,27.766500,33.716500,0.097,20,3,4
2373,2026-03-27 21:00:00+00:00,28.1165,86.0,0.0,1007.61414,34.205208,13.104197,200.92458,27.466501,33.316498,0.097,21,3,4
2374,2026-03-27 22:00:00+00:00,27.7665,88.0,0.0,1008.41296,34.286777,10.308830,204.77512,27.266500,32.866497,0.097,22,3,4
2375,2026-03-27 23:00:00+00:00,27.5665,89.0,0.0,1008.81200,34.271670,8.404285,226.73567,27.066500,32.466500,0.097,23,3,4

In [17]:
import numpy as np
def fig_scatter_temp_hum(data) -> go.Figure:
    """Scatter temperature vs humidité, colorié par heure."""
    data_sample = data[["temperature_2m", "relative_humidity_2m", "hour",
                 "precipitation", "apparent_temperature", "temperature_80m"]].dropna()
 
    fig = px.scatter(
        data_frame=data_sample,
        x="temperature_2m",
        y="relative_humidity_2m",
        color="hour",
        color_continuous_scale="RdYlBu_r",
        labels={
            "temperature_2m":       "Température (°C)",
            "relative_humidity_2m": "Humidité (%)",
            "hour":                 "Heure",
        },
        opacity=0.5,
        hover_data={"apparent_temperature": ":.1f", "precipitation": ":.2f"},
    )
    fig.update_traces(marker=dict(size=4))
    fig.update_layout(
        template="plotly_white",
        height=340,
        margin=dict(l=10, r=10, t=10, b=10),
        coloraxis_colorbar=dict(title="Heure", thickness=12, len=0.8),
    )
    return fig
 
 
def fig_wind_rose(data) -> go.Figure:
    """Rose des vents à partir de wind_direction_80m et wind_speed_80m."""
    wd = data["wind_direction_80m"].dropna()
    ws = data["wind_speed_80m"].dropna()
 
    # Aligne les index
    valid = data[["wind_direction_80m", "wind_speed_80m"]].dropna()
    directions = valid["wind_direction_80m"].values
    speeds     = valid["wind_speed_80m"].values
 
    # Découpe en 16 secteurs
    n_sectors = 16
    sector_size = 360 / n_sectors
    sectors = [f"{int(i * sector_size)}°" for i in range(n_sectors)]
    speed_bins  = [0, 5, 10, 15, 20, 50]
    speed_labels= ["0-5", "5-10", "10-15", "15-20", ">20"]
    speed_colors= ["teal", "blue", "#347dbc","coral", "purple"]
 
    fig = go.Figure()
    for i, (lo, hi) in enumerate(zip(speed_bins[:-1], speed_bins[1:])):
        mask = (speeds >= lo) & (speeds < hi)
        d_bin = directions[mask]
        counts = np.zeros(n_sectors)
        for angle in d_bin:
            idx = int((angle % 360) / sector_size) % n_sectors
            counts[idx] += 1
        fig.add_trace(go.Barpolar(
            r=counts,
            theta=sectors,
            name=f"{speed_labels[i]} km/h",
            marker_color=speed_colors[i],
            opacity=0.85,
        ))
 
        fig.update_layout(
            template="plotly_white",
            height=340,
            margin=dict(l=10, r=10, t=10, b=10),
            polar=dict(
                radialaxis=dict(showticklabels=False, ticks=""),
                angularaxis=dict(direction="clockwise", rotation=90),
            ),
            legend=dict(orientation="h", y=-0.08, font=dict(size=11)),
        )
    return fig
 
 
def fig_boxplot_by_hour(data) -> go.Figure:
    """Boxplot de la température par heure de la journée."""
    fig = go.Figure()
    for h in range(24):
        vals = data[data["hour"] == h]["temperature_2m"].dropna()
        fig.add_trace(go.Box(
            y=vals,
            name=str(h),
            marker_color="coral",
            line_color="coral",
            showlegend=False,
            boxmean="sd",
        ))
    fig.update_layout(
        template="plotly_white",
        height=320,
        margin=dict(l=10, r=10, t=10, b=10),
        xaxis=dict(title="Heure de la journée"),
        yaxis=dict(title="Température (°C)", gridcolor="#ff0000"),
    )
    return fig

In [18]:
fig_scatter_temp_hum(data=data_meteo)

In [19]:
fig_wind_rose(data=data_meteo)

In [20]:
fig_boxplot_by_hour(data=data_meteo)

In [21]:
def fig_precipitation_bar(data) -> go.Figure:
    """Barres de précipitations journalières, colorié par intensité."""
    rainy = data[data["precipitation"] > 0.0].copy().dropna()
    rainy["color"] = rainy["precipitation"].apply(
        lambda x: "blue" if x < 1 else "teal" if x < 3 else "coral"
        )
    fig = go.Figure(go.Bar(
        x=rainy["hour"],
        y=rainy["precipitation"],
        marker_color=rainy["color"],
        hovertemplate="%{x|%d %b}<br><b>%{y:.1f} mm</b><extra></extra>",
    ))
    fig.update_layout(
        template="ggplot2",
        height=280,
        margin=dict(l=10, r=10, t=10, b=10),
        xaxis=dict(title="Heure"),
        yaxis=dict(title="Precipitation(mm)", gridcolor="#c8ba90"),
        showlegend=False,
    )
    return fig

In [22]:
fig_precipitation_bar(data=data_meteo)

* ### Matrice de Correlation

In [27]:
# Matrice de corrélation
CORR_COLS = [
    "temperature_2m", "relative_humidity_2m", "precipitation",
    "surface_pressure", "apparent_temperature", "wind_speed_80m",
    "temperature_80m", "soil_temperature_18cm", "soil_moisture_3_to_9cm",
]
corr_cols_present = [c for c in CORR_COLS if c in data_meteo.columns]
corr_matrix = data_meteo[corr_cols_present].dropna().corr().round(3)
corr_labels_short = {
    "temperature_2m":         "temp 2m",
    "relative_humidity_2m":   "humidité",
    "precipitation":          "précip",
    "surface_pressure":       "pression ",
    "apparent_temperature":   "température apparente",
    "wind_speed_80m":         "vent vitesse 80m",
    "temperature_80m":        "temperature 80m",
    "soil_temperature_18cm":  "sol temp",
    "soil_moisture_3_to_9cm": "sol hum",
}
corr_display = [corr_labels_short.get(c, c) for c in corr_cols_present]

In [28]:

def fig_correlation_heatmap() -> go.Figure:
    """Heatmap de corrélation annotée."""
    z    = corr_matrix.values
    text = [[f"{v:.2f}" for v in row] for row in z]
 
    fig = go.Figure(go.Heatmap(
        z=z,
        x=corr_display,
        y=corr_display,
        text=text,
        texttemplate="%{text}",
        textfont=dict(size=11),
        colorscale=[
            [0.0,  "#D85A30"],
            [0.5,  "#ffffff"],
            [1.0,  "#378ADD"],
        ],
        zmid=0,
        zmin=-1, zmax=1,
        colorbar=dict(title="r", thickness=12, len=0.8),
        hovertemplate="%{y} / %{x}<br><b>r = %{z:.3f}</b><extra></extra>",
    ))
 
    fig.update_layout(
        template="plotly_white",
        height=360,
        margin=dict(l=10, r=10, t=10, b=10),
        xaxis=dict(side="bottom", tickangle=-30),
        yaxis=dict(autorange="reversed"),
    )
    return fig

In [29]:
fig_correlation_heatmap()